services:
  # Servicio de la aplicación Spring Boot
  spring-app:
    build:
      context: .
    container_name: spring-app
    ports:
      - "${SPRING_APP_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
