spring:
  application:
    name: ecommerce
    services:
      safe-url: "*"
  profiles:
    include: ${ENVIRONMENT}
  h2:
    console:
      enabled: true
      path: "/h2"

  datasource:
    url: jdbc:h2:mem:${DB_NAME};DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

    hikari:
      pool-name: h2-ecommerce-pool
      auto-commit: true
      connection-timeout: 60000
      idle-timeout: 120000
      maximum-pool-size: 60
      minimum-idle: 20
      max-lifetime: 600000
      acquisition-timeout: 30000
      detect-statement-leaks: false
      allow-pool-suspension: false
      catalog: ecommerce

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    org.hibernate: WARN