server:
  port: 8080
  servlet:
    context-parameters:
      redirect-to-https: true

springdoc:
  api-docs:
    path: /api
  swagger-ui:
    path: /swagger-ui.html
  paths-to-exclude: /swagger-resources/**